# ================================================== #
#          BorderControl Configuration File          #
#                By ItzMOJAHIDE                      #
# ================================================== #

# You can use Minecraft color codes with the '&' symbol.
# For example: '&a' is green, '&6' is gold, '&l' is bold.

# The prefix that appears before most plugin messages.
plugin_prefix: "&6[BorderControl] &r"

# --- Border Settings ---
border_settings:
  # When an OP uses "/border set <size>" without specifying a time,
  # how many seconds should the border change take?
  # Set to 0 for an instant change by default.
  default_change_duration: 60

# --- Effects Settings ---
effects:
  # Enable the full-screen totem pop-up animation when the border changes.
  totem_animation: true

  # Enable a sound effect when the border changes.
  sound:
    enabled: true
    # You can change this to any sound from Minecraft!
    # A list can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    # Example: ENTITY_ENDER_DRAGON_GROWL
    sound_name: "ITEM_TOTEM_USE"
    # Volume of the sound (1.0 is normal).
    volume: 1.0
    # Pitch of the sound (1.0 is normal).
    pitch: 1.0

# --- Messages ---
# Customize the messages sent by the plugin.
# Placeholders like %size% and %seconds% will be replaced with the real values.
messages:
  no_permission: "&cYou do not have permission to use this command."
  reload_success: "&aConfiguration has been reloaded successfully."
  logo_updated: "&aLogo URL has been updated."
  current_size: "&bThe current border size is %size%x%size%."
  border_set_instant: "&aWorld border has been instantly set to %size%x%size%."
  border_set_smooth: "&aWorld border is now changing to %size%x%size% over %seconds% seconds."
  invalid_number: "&cThat is not a valid number."
  unknown_command: "&cUnknown command. Use /border help for a list of commands."

# --- Command Toggles ---
# Enable or disable specific commands.
commands:
  admin:
    border_set: true
    border_reload: true
    border_logo: true
    border_help: true
  user:
    border_see: true
    border_help: true
