# ================================================== #
#          BorderControl Configuration File          #
#                By ItzMOJAHIDE                      #
# ================================================== #

plugin_prefix: "&6[BorderControl] &r"

# --- Border Settings ---
border_settings:
  # When an OP uses "/border set <world> <size>" without specifying a time,
  # how many seconds should the border change take?
  # Set to 0 for an instant change by default.
  default_change_duration: 60

# --- On-Screen Title Messages ---
title_messages:
  # Set to true to show the big title message on screen. Set to false to hide it.
  enabled: true
  timings:
    fade_in: 1
    stay: 5
    fade_out: 1
  expand:
    title: "&aWorld Border Expanding"
    subtitle: "&fNew Size: %size% | Time: %time%s"
  shrink:
    title: "&cWorld Border Shrinking"
    subtitle: "&fNew Size: %size% | Time: %time%s"

# --- Special Effects ---
# These effects happen at the same time as the title message (if enabled).
effects:
  totem_animation: true
  particles:
    enabled: true
    particle_type: "TOTEM_OF_UNDYING"
    count: 75
  sound:
    enabled: true
    sound_name: "ITEM_TOTEM_USE"
    volume: 1.0
    pitch: 1.0

# --- Messages ---
# Placeholders: %size%, %seconds%, %world%
messages:
  no_permission: "&cYou do not have permission to use this command."
  reload_success: "&aConfiguration has been reloaded successfully."
  current_size: "&bThe current border size is %size%x%size%."
  # Message for when a world doesn't exist.
  world_not_found: "&cThe world '%world%' could not be found."
  # Messages to include the world name.
  border_set_instant: "&aWorld border for '%world%' has been instantly set to %size%x%size%."
  border_set_smooth: "&aWorld border for '%world%' is now changing to %size%x%size% over %seconds% seconds."
  invalid_number: "&cThat is not a valid number."
  unknown_command: "&cUnknown command. Use /border help for a list of commands."

# --- Command Toggles ---
commands:
  admin:
    border_set: true
    border_reload: true
    border_help: true
  user:
    border_see: true
    border_help: true
