# ================================================== #
#          BorderControl Configuration File          #
#                By ItzMOJAHIDE                      #
# ================================================== #

# You can use Minecraft color codes with the '&' symbol.
plugin_prefix: "&6[BorderControl] &r"

# --- Border Settings ---
border_settings:
  # When an OP uses "/border set <size>" without specifying a time,
  # how many seconds should the border change take?
  # Set to 0 for an instant change by default.
  default_change_duration: 60

# --- Effects Settings ---
effects:
  # Enable the full-screen totem pop-up animation when the border changes.
  totem_animation: true

  # --- Particles ---
  particles:
    enabled: true
    # You can change this to any particle from Minecraft!
    # A list is here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    # Examples: FLAME, HEART, DRAGON_BREATH
    particle_type: "TOTEM_OF_UNDYING"
    # How many particles to spawn.
    count: 75

  # --- Sound ---
  sound:
    enabled: true
    # Sound list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    sound_name: "ITEM_TOTEM_USE"
    volume: 1.0
    pitch: 1.0

# --- Messages ---
messages:
  no_permission: "&cYou do not have permission to use this command."
  reload_success: "&aConfiguration has been reloaded successfully."
  current_size: "&bThe current border size is %size%x%size%."
  border_set_instant: "&aWorld border has been instantly set to %size%x%size%."
  border_set_smooth: "&aWorld border is now changing to %size%x%size% over %seconds% seconds."
  invalid_number: "&cThat is not a valid number."
  unknown_command: "&cUnknown command. Use /border help for a list of commands."

# --- Command Toggles ---
commands:
  admin:
    border_set: true
    border_reload: true
    border_help: true
  user:
    border_see: true
    border_help: true
