# -------------------------------------------------- #
#               BorderControl Configuration          #
# -------------------------------------------------- #

# The logo URL to be displayed (optional)
logo_url: "https://example.com/logo.png"

# --- Command Settings ---
# Enable or disable specific commands for your server.
commands:
  admin:
    border_set: true
    border_reload: true
    border_logo: true
    border_help: true
  user:
    border_see: true
    border_help: true
